### ISSUE TITLE
Add front-end form validation and error message on Login and Signup component.

### ISSUE THREAD

**Issue by rohit267** [rohit267/akshepya#1]

**Comment by codezerro** [comment]
Rohit, I review your project and i'm interested to contribute on it. But now my exam knocking my door. Can i contribute any issues or future or bug after my exam?
Thank you.

**Comment by rohit267** [comment]
No worries, I will create more issues in the future, will leave basic things to contribute for others. Focus on exams. You can develop features Ask question page etc.

**Comment by codezerro** [comment]
Thank you
