### ISSUE TITLE
Make a Logo

### ISSUE THREAD

**Issue by rohit267** [rohit267/akshepya#12]
Make a logo, should be in PNG. written 'akShepya, open to questions' vertically

**Comment by ChugilC** [comment]
Can you please elaborate on that like if you want to add it in the code or just you need the png file ?

**Comment by rohit267** [comment]
> Can you please elaborate on that like if you want to add it in the code or just you need the png file ?

If you can make the logo and add to the code, it would be great. Make sure you do it in other branch.

**Comment by ChugilC** [comment]
> > Can you please elaborate on that like if you want to add it in the code or just you need the png file ?
> 
> If you can make the logo and add to the code, it would be great. Make sure you do it in other branch.

Ok brother

**Comment by rohit267** [comment]
> > > Can you please elaborate on that like if you want to add it in the code or just you need the png file ?
> > 
> > 
> > If you can make the logo and add to the code, it would be great. Make sure you do it in other branch.
> 
> Ok brother

any update?

**Comment by harrylongia** [comment]
I would like to work on this. assign it to me

**Comment by rohit267** [comment]
> I would like to work on this. assign it to me

Assigned.

**Comment by harrylongia** [comment]
I am not able to "npm i"...i created .env file and also added PORT=5000. (dont need mongourl and jwt secret for logo)

**Comment by rohit267** [comment]
> I am not able to "npm i"...i created .env file and also added PORT=5000. (dont need mongourl and jwt secret for logo)

cd front-end then npm start . This will start the front-end only
